spring:
  application:
    name: hotel_API
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 37913004901-oivf9svfmvuv02slrm7udsvd6tv792b2.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/api/v1/auth/google/callback"
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  datasource:
    url: jdbc:postgresql://localhost:5432/SpringHotelBD
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt-secret: 63a3101ac990aa2382bc6233189c036035fff09b46f0e18834614273e252debd
  jwt-expiration-time: 86400000

admin:
  fullName: Admin User
  country: AD
  documentNumber: 123456778-9
  phoneNumber: 12345678
  email: admin@hotel.com
  userName: adminUser
  password: 49SuF7B9Wtzd